baseURL = "https://miraiaxis.com/blog/"
title = "MIRAI AXIS ブログ"
theme = "PaperMod"
defaultContentLanguage = "ja"
languageCode = "ja-jp"
enableRobotsTXT = true

# ✅ Hugo 0.128+：paginate → pagination.pagerSize
[pagination]
  pagerSize = 10

[params]
[params.assets]
  customCSS = ["css/custom.css"]
  env = "production"
  description = "事業開発・ブロックチェーン・実装メモ"
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowToc = true
  TocOpen = true
  DateFormat = "2006-01-02"

[menu]
  [[menu.main]]
    name = "メイン"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "ブログ"
    url = "/blog/"
    weight = 2

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params.assets]
  customCSS = ["css/custom.css"]