baseURL = "https://miraiaxis.com/blog/"
title = "MIRAI AXIS ブログ"
theme = "PaperMod"
defaultContentLanguage = "ja"
languageCode = "ja-jp"
enableRobotsTXT = true

[pagination]
  pagerSize = 10

[params]
  env = "production"
  description = "事業開発・ブロックチェーン・実装メモ"
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowToc = true
  TocOpen = true
  DateFormat = "2006-01-02"

[params.assets]
  customCSS = ["css/custom.css"]

[menu]
  [[menu.main]]
    name = "メイン"
    url  = "https://miraiaxis.com/"  # ← フルURLに
    weight = 1
  [[menu.main]]
    name = "ブログ"
    url  = "/"                        # ← relURLで /blog/ に正規化される
    weight = 2


[outputs]
  home = ["HTML", "RSS", "JSON"]

