baseURL = "https://miraiaxis.com/blog/"
title = "MIRAI AXIS ブログ"
theme = "PaperMod"
defaultContentLanguage = "ja"
languageCode = "ja-jp"
enableRobotsTXT = true

[pagination]
  pagerSize = 10

[params]
  mainSections = ["posts"]

[menu]
  [[menu.main]]
    name = "メイン"
    url  = "https://miraiaxis.com/"   # フルURL
    weight = 1
  [[menu.main]]
    name = "ブログ"
    url  = "/"                        # /blog/ に正規化される
    weight = 2

[outputs]
  home = ["HTML", "RSS", "JSON"]


